services:
  bookmark-db:
    image: postgres:16-alpine
    container_name: bookmark-db
    env_file:
      - postgres/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - bookmark-network
    volumes:
      - bookmark_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bookmark-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - bookmark-network
    volumes:
      - redis_data:/data
    restart: unless-stopped

  bookmark-service:
    image: huypham053/bookmark-service:0cd6fb0
    depends_on:
      bookmark-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - bookmark-service/.env
    networks:
      - bookmark-network
    volumes:
      - ./bookmark-service/keys:/app/keys
    restart: unless-stopped

  portal:
    image: ebvn/bookmark-app-portal:mono
    container_name: bookmark-portal
    depends_on:
      - bookmark-service
    networks:
      - bookmark-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: bookmark-nginx
    depends_on:
      - bookmark-service
      - portal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bookmark-network
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: bookmark-cloudflared
    env_file:
      - ./config/cloudflared.env
    command: tunnel --no-autoupdate --protocol http2 run
    networks:
      - bookmark-network
    restart: unless-stopped

volumes:
  bookmark_db_data:
  redis_data:
  cloudbeaver_data:

networks:
  bookmark-network:
    driver: bridge

